### PR TITLE
created camp note model and methods to get, add, remove notes from location camps

### PR DESCRIPTION
**Pull request by addelian**
@wilsont3 hoping for your thoughts on this. This ended up being a lot heftier than I expected since the camp page didn't have any other functionality quite like this before adding it. The methods all seem to be firing correctly and at the right times, but it's not finding the endpoints I tried to create (I'm seeing 404s on the POST and GET calls when trying to actually submit the camp notes). I'm sure something's not 100% lined up but I'm struggling to pinpoint it.

### CODE REVIEW

**Comment by wilsont3** [comment]
@addelian That was a good call on your part to start working on this as I had not created the table in the database (which makes sense why there were 404 errors.  I called the table "location_camp_notes" and I added the following columns: id (integer); location_camp_id (integer); note (string); created_at (datetime); updated_at (datetime).  I think these are all the columns that we need, but let me know if you think otherwise.

**Comment by addelian** [comment]
@wilsont3 I think those columns will be plenty; I don't think we necessarily need updated_at if we're matching the Client Detail notes page, as that page doesn't show updated dates, and updated_at isn't a parameter on the client Notes model. Either way, I updated the fields so everything lines up nicely, but from a testing perspective, this still isn't working for me. Though, I don't know that I'm aware of what steps I need to take to actually pull updated tables down to my local testing environment, as I don't see that there were any changes in this repo, and restarting my server didn't seem to do the trick.

**Comment by wilsont3** [comment]
@addelian That was my fault.  I forgot to add the table in the TEST environment.  This should now be in place for you to use.

**Comment by addelian** [comment]
@wilsont3 Thanks, that fixed the testing! Okay, I made a few more changes but I'm still not 100% there. The note is saving, but somewhere in between the note being built in the camp-note-component and main.service submitting the POST call, I am losing the content of what's being built in the component. The data arrives to insertCampNote (in main.service.ts) intact, but in the POST, the actual content that was built by the component (the location_camp_id and the note string) are stripped out, while the automated pieces maintain (id & created_at). I structured the insertCampNote function in the same fashion as other functions in the main.service, but something clearly isn't connecting how I expect it to. Any thoughts?

**Comment by wilsont3** [comment]
Let me take a look this afternoon and get back to you on that

**Review by wilsont3 — APPROVED** [review]
So for the GetCampNotes, I realized that I had not set up the API call for that and, once I did, that worked really well.  Then, for the inserting of camp notes, the parameter name on the service API call (note instead of location_camp_note) was what was stopping everything inserting.  Please pull down my changes to this branch and make sure everything makes sense and then you can merge it in.

**Comment by wilsont3** [comment]
@addelian Thanks so much for the help on this, too, by the way!

**Comment by addelian** [comment]
@wilsont3 Thanks for your patience on this - I pulled it down and compared your updates. I understand the updates - good to know on the naming convention of the API parameters! Thanks again for your help.

**Pull request merged**
