### PR TITLE
aligned forms, moved back buttons to bottom

### PR DESCRIPTION
**Pull request by john-william-cross**
fixed problems on last pull request (I think!)

### CODE REVIEW

**Comment by wilsont3** [comment]
Go ahead and just push the changes you made to the same branch and the other pull request will update on its own.  I am going to close this commit so that we can just use the original pull request.  Let me know if you have any questions on this.

**Comment by john-william-cross** [comment]
Hey, just got back into town last night. Which branch do you want me to
push changes to? Also, do you still want me to change the right-aligned
elements from using a table to using the align function? I originally tried
that but couldn't get it to work, hence my use of tables. But I'm sure I
can figure it out. Let me know, I have time during the day today to work on
it.

John

**Comment by wilsont3** [comment]
Push your changes to whatever branch it was that you first pushed. I think
it was something like align-forms-to-right. You do not need to create a new
branch like you did with branch-name-november-1.

If you have some time, look into not using tables and then if you can't
figure it out, use the tables. I think you can do an align on the div tag
or something.

Tim

**Comment by john-william-cross** [comment]
Here are the pull requests I've made:
[image: Screen Shot 2019-11-05 at 10.55.22 AM.png]

I'm still confused on what changes you want pushed and which ones you
don't. I just merged the one you approved two days ago. Other than that, I
think it'd be easier at this point for me to just make a new branch from
master and move any other back buttons down and do form alignment using
align on the div tag as you suggested... what do you think?

**Comment by john-william-cross** [comment]
Also, when viewing the master branch in my browser I am not seeing an end
route/sign out button...

**Comment by wilsont3** [comment]
Can you give me a call?

**Comment by wilsont3** [comment]
My number is 5152052353.

**Comment by john-william-cross** [comment]
Yeah what is your number

**Comment by john-william-cross** [comment]
Called ya, call me back any time

**Comment by wilsont3** [comment]
I got the voicemail, but don't think it saved as a call. If you can, just
call me again please. Thanks!

**Pull request closed without merging**
