### PR TITLE
Expected arrival time subheading added

### PR DESCRIPTION
**Pull request by addelian**
Tim, I believe everything is setup from the .ts files through the .html to display data about the expected_arrival_time once information is actually added. I followed the same format as the "notes" attribute. That said, I don't know if there's actually any information in that table on the backend yet, so I'm not sure if it's working or not. Thanks for taking a peek!

### CODE REVIEW

**Comment by john-william-cross** [comment]
Hey Tim,

Some of my Joppa files got removed from my computer so I'm currently unable
to work on the cards I assigned myself to... I'm not sure what exactly is
missing. Should I be able to just create a branch from master?

John

**Comment by wilsont3** [comment]
Hi John,

Yes you should just be able to pull the needed files back down from the
master branch.

Tim

**Comment by addelian** [comment]
@wilsont3 Whoops - I totally misunderstood that this was something that people building / updating the camps would plug in on the front end. Than you for clarifying how that data flow works! Everything should be in working order now.

**Comment by addelian** [comment]
@wilsont3 thanks for the reminder on input types--I'm sure I heard about it at one point, but I clearly forgot about that attribute at some point along the way :)

**Review by wilsont3 — APPROVED** [review]
@addelian This looks great.  Go ahead and merge this when you get a chance.

**Pull request merged**
