### PR TITLE
referrals / resources front end built out, some api functionality with errors

### PR DESCRIPTION
**Pull request by addelian**
@wilsont3 Hoping for some guidance on this one when you have time. I noted that this was basically the same idea as the recent tent functionality, so I followed most of my old work on that branch, but the build is failing at some point, saying that the modal import isn't recognized (which I know is not the case, almost certainly a typo / mislabel somewhere). Because the build is failing, I haven't been able to test the visual appearance. If you could please help me pinpoint why the build is failing, I can take back over and finish cleaning up the front end appearance. Thank you in advance!

### CODE REVIEW

**Comment by wilsont3** [comment]
@addelian I found that the ReferralsResourcesComponent was not added to the app.module.ts file.  When I create new component, as is in the README.md file, I use ng generate component {component_name}.

**Comment by addelian** [comment]
@wilsont3 Ah, thanks for pointing that out! That's what I get for not reading thoroughly. Process is a little different in React. I'll keep working with these changes. Thanks again!

**Comment by addelian** [comment]
@wilsont3 From a visual standpoint, this seems to be good to go. It's still not saving off. I've double-checked the logic compared to other functions within the Client Service but something's still not clicking. It's getting a 404 on the endpoints I'm calling, I'm not sure if there's something in the back end that those are supposed to align with but I've not been able to find anything to confirm either way.

**Review by wilsont3 — APPROVED** [review]
@addelian As you said, I just needed to update the API paths as I called the table client_referrals.  This should now be working.  Thank you for doing so much of the legwork on this!

**Pull request merged**
