### PR TITLE
removed unused requested items, added number field to Mail requested …

### PR DESCRIPTION
**Pull request by addelian**
…item, added ability to show multiple camps from one parking spot if parking coordinates register as the same within 0.00005 degrees

### CODE REVIEW

**Comment by addelian** [comment]
@wilsont3 Original plan was to push these up in separate branches for separate PRs, but the parking functionality came together quicker than I expected. If we hit any hiccups in the review process and you want me to pull out the "requested item" stuff so we can get those moved along, just let me know and I can get that taken care of. Thanks!

**Review by wilsont3 — APPROVED** [review]
@addelian These all look good.  Go ahead and merge these in and then I will push up to TEST for Megan and Tom to test.  Thanks for the help!

**Comment by wilsont3** [comment]
One final comment. I saw that you are just showing the camps on the parking map now.  Do you think we need to show the parking spot and then all the camps (just add parking spot at the beginning?)

**Comment by addelian** [comment]
@wilsont3 Good call, I think I must have accidentally deleted that when I was plugging in everything else. I'll add that in at the beginning of the URL now. Thanks for catching that!

**Comment by addelian** [comment]
@wilsont3 Updated. Thanks again for taking a look!

**Pull request merged**
